### ISSUE TITLE
Is PRISMS-Fatigue available for BCC

### ISSUE THREAD

**Issue by mubellyb** [prisms-center/Fatigue#25]
Hi,

Thanks for sharing. But I have a question. 

You have mentioned that PRISMS-Fatigue only for cubic crystal structure at present in the video on YouTube. I want to know if PRISMS-Fatigue can only be used for fcc, or both bcc(or bcq like Martensite steel) and fcc can be calculated.

Hope for your answer.

**Comment by StopkaKris** [comment]
Hi,

Thanks for your question. Right now, the workflows are not set up to support computation of FIPs for the BCC crystal structure, but rather only for FCC. However, this would require minimal change to the code. The script `generate_microstructures.py` has a section where slip plane normals are defined as shown below:
`
FCC_OCT_NORMALS = np.asarray([[1,1,1],
[-1,1,1],
[1,1,-1],
[1,-1,1]]) / (3**0.5)
`

This is where we specify on what slip planes the FIPs should be computed. You can then search for where this variable is called in the script to see where the next change must be made. So to compute FIPs for BCC, a section must be added to reflect the BCC slip planes. There may be some other places, however, that must also be edited. For instance, the `calculate_FIPs.py` script may also need to be edited.

Another note is that the slip plane and slip directions defined in these scripts MUST match those defined in PRISMS-Plasticity, in terms of order relative to the global x,y,z directions. Otherwise, these scripts will average FIPs over incorrect slip systems and elements.

Best regards,
Kris
